### ISSUE TITLE
如何调整输入字符颜色和背景

### ISSUE THREAD

**Issue by Confucian-e** [drbbr/fcitx5-dracula-theme#4]
我安装配置好后输入为这种效果
![image](https://github.com/drbbr/fcitx5-dracula-theme/assets/46948182/e44d322a-8a3d-4f28-afc2-e38188a70aec)

如果我想达到以下效果，应该如何配置参数
![image](https://github.com/drbbr/fcitx5-dracula-theme/assets/46948182/7ee96564-136d-42b8-a28f-3db04436fd58)

**Comment by drbbr** [comment]
有一点忘记了 可以试试把HighlightBackgroundColor删掉看看
