### ISSUE TITLE
如何调整背景透明度

### ISSUE THREAD

**Issue by LAST7** [drbbr/fcitx5-dracula-theme#5]
如视频所示，透明度似乎有些过低了

https://github.com/drbbr/fcitx5-dracula-theme/assets/96737659/2971fb19-87ae-437a-b875-ea8ab7bbe912

~~我也不太确定到底是完全不透明还是透明度过低~~

**Comment by drbbr** [comment]
感觉你这个有点像毛玻璃的效果🤔 但是我的设置里应该没这个相关的东西
如果感觉透明度不够的话。可以自己开个ps，根据[panel.png](https://github.com/drbbr/fcitx5-dracula-theme/blob/main/panel.png)的颜色去做一个透明度比[paneltrans.png](https://github.com/drbbr/fcitx5-dracula-theme/blob/main/paneltrans.png)更低的背景。

**Comment by LAST7** [comment]
> 感觉你这个有点像毛玻璃的效果thinking 但是我的设置里应该没这个相关的东西 如果感觉透明度不够的话。可以自己开个ps，根据[panel.png](https://github.com/drbbr/fcitx5-dracula-theme/blob/main/panel.png)的颜色去做一个透明度比[paneltrans.png](https://github.com/drbbr/fcitx5-dracula-theme/blob/main/paneltrans.png)更低的背景。

经你这么一说我明白了，是我 picom 里有模糊透明窗口背景的效果，把 fcitx exclude 了之后就好了，多谢解惑
